
services:

  file-api:
    container_name: file-api
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  web-client:
    container_name: web-client
    build:
      context: ./client/web-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - file-api
    environment:
      - "VITE_API_URL=http://file-api:3000"
