
services:

  deletion-worker:
    container_name: deletion-worker
    build:
      context: ./server/
      dockerfile: Dockerfile.deletion-worker
    depends_on:
      - file-api

  file-api:
    container_name: file-api
    build:
      context: ./server/
      dockerfile: Dockerfile.file-api
    ports:
      - "3000:3000"

  web-client:
    container_name: web-client
    build:
      context: ./client/web-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - file-api
    environment:
      - "VITE_API_URL=http://localhost:3000"
