FROM node:24-alpine AS build

# Create app directory
WORKDIR /app

# Copy entire source
COPY . .

WORKDIR /app/apps/deletion-worker
RUN yarn install
RUN yarn build

WORKDIR /app/apps/postgres-manager/prisma
RUN npx prisma generate

WORKDIR /app/apps/deletion-worker

# Start using tsconfig-paths
CMD ["node", "dist/apps/deletion-worker/src/index.js"]
